### ISSUE TITLE
[hardware] 재료 구매

### ISSUE THREAD

**Issue by sm-koeunseo** [sm-koeunseo/Smart-Farm-Hanni#4]
📥 프로젝트 장비 및 센서 구매

장비
✅ 리빙박스 2개
✅ 화분 3개
✅ 생장 LED
✅ 흙
✅ 삽 1개
✅ 마사토 2개
✅ 화분 거름망
✅ 지지대
✅ 아날로그 온습도계
✅ 워터펌프 6개
✅ 호스 6개
❎ 물통 2개

식물
✅ 바질
✅ 강낭콩

센서
✅ 온습도 센서 2개
✅ 수위 센서
✅ 토양수분센서 6개

**Comment by sm-koeunseo** [comment]
Apr. 8th

에픽토이
- 리빙박스 (https://smartstore.naver.com/epicaqua/products/9335713829), 화이트 투명 자이언트, 49800원, 2개, 97800원

플아가든
- 식물등 LED 식물조명 (https://smartstore.naver.com/peula_garden/products/3772843135), PU102 초고출력(30W) 백색/주광색, 39600원, 1개, 39600원
- 키소켓 코드선 220v (1.4M), 6000원, 1개, 6000원
- 배송비 3000원

총 가격 : 146,400원

**Comment by minzero31** [comment]
Apr. 16th

에듀이노
* 토양 수분감지 센서 모듈(https://m.eduino.kr/product/detail.html?product_no=84&cate_no=27), 2200원, 3개, 6600원
* 수위 측정 센서 모듈(https://m.eduino.kr/product/detail.html?product_no=106&cate_no=27), 1900원, 1개, 1900원
* 배송비 3000원

테크선전
* 미니모터 펌프 수중용 워터펌프(http://m.techshenzhen.com/goods/goods_view.php?goodsNo=1000000356), 1100원, 3개, 3300원
* 워터펌프 실리콘 호스1m(http://m.techshenzhen.com/goods/goods_view.php?goodsNo=1000000337), 2400원, 3개, 7200원
* 배송비 3000원

디바이스마트
* 온습도센서 DHT22(https://www.devicemart.co.kr/goods/view?no=15285137&NaPm=ct%3Dlxhcylou%7Cci%3Dcheckout%7Ctr%3Dppc%7Ctrx%3Dnull%7Chk%3Df2807a806998d57a45c014f149d48400384eed17), 2530, 2개, 5060원
* 배송비 2700원

쿠팡
* 스위트바질모종10개(https://link.coupang.com/a/bFRqFL), 8170원, 1개, 8170원

네이버
* 강낭콩 모종 5개+배송비, 7200원

총 가격 : 48,130원

**Comment by sm-koeunseo** [comment]
Apr. 8th

쿠팡
- 아날로그 온습도계(https://link.coupang.com/a/bFYW2d), 1460원, 1개, 1460원

쿠팡 화분월드
- 화분월드 식물 코팅 지주대 2.8mm x 70cm(https://link.coupang.com/a/bFYW96), 5400원, 1개, 5400원
- 화분월드 대용량 직사각 텃밭상자 + 받침 3세트(https://link.coupang.com/a/bFYXgV), 20280원, 1개, 20280원
- 화분월드 흙사랑 배양토(https://link.coupang.com/a/bFYXnZ), 12300원, 1개, 12300원

총 가격 : 39,440원

**Comment by sm-koeunseo** [comment]
May. 26th

쿠팡
- 콤탭 멀티 콘센트 10A 2구 SHM-COM2(https://link.coupang.com/a/bC449L), 5980원, 1개, 5980원

총 가격 : 5,980원

**Comment by sm-koeunseo** [comment]
아이씨뱅큐

- 라즈베리파이 IoT 키트(https://www.icbanq.com/P013149476), 131000원, 3개, 393,000원
- 라즈베리파이 5 , Raspberry pi 5 Model 8GB(https://www.icbanq.com/P015956550), 107000원, 3개, 321000원

총 가격 : 714,000원
